### ISSUE TITLE
 Could not find a package configuration file provided by "upo_msgs"

### ISSUE THREAD

**Issue by Zhousiyuhit** [robotics-upo/upo_nav_irl#1]
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "upo_msgs" with any
  of the following names:

    upo_msgsConfig.cmake
    upo_msgs-config.cmake

  Add the installation prefix of "upo_msgs" to CMAKE_PREFIX_PATH or set
  "upo_msgs_DIR" to a directory containing one of the above files.  If
  "upo_msgs" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  upo_nav_irl/CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/siyuzhou/upo_nav_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/siyuzhou/upo_nav_ws/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1

**Comment by david-alejo** [comment]
Dear Zhousiyuhit

This package is dependent on another package of our research group. Link:

https://github.com/robotics-upo/upo_robot_navigation

Please try to clone and compile it. In this way, you should be able to have our irl package working.

Best,

**Comment by Zhousiyuhit** [comment]
Thanks for replying my question, and now I have encountered another question:

In file included from /home/siyuzhou/upo_nav_ws/src/upo_robot_navigation/upo_rrt_planners/src/ros/ValidityChecker3.cpp:2:0:
/home/siyuzhou/upo_nav_ws/src/upo_robot_navigation/upo_rrt_planners/include/upo_rrt_planners/ros/ValidityChecker3.h:50:44: fatal error: path_prediction/PathPrediction.h: No such file or directory
 #include <path_prediction/PathPrediction.h>
                                            ^
compilation terminated.

**Comment by Zhousiyuhit** [comment]
Thanks for replying my question~
